version: '3'

services:

  #  start caddy, and mount document root to /dist locally, and Caddyfile to a local configuration file, Caddyfile
  caddy:
    image: 'caddy:2.4.6-alpine'
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./dist:/dist
      - ./Caddyfile:/etc/caddy/Caddyfile
